### ISSUE TITLE
Convert Rapport samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#1]
https://www.bipm.org/en/publications/rapports-bipm/

https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2019-05.pdf

https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2020-02.pdf

**Comment by ronaldtse** [comment]
Ping @anermina could you help with these? Thanks!

**Comment by anermina** [comment]
https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2019-05.pdf has already been converted in https://github.com/metanorma/bipm-si-brochure/blob/master/sources/mep-candela-rapport.adoc. 

https://www.bipm.org/utils/common/pdf/rapportBIPM/RapportBIPM-2020-02.pdf is converted in https://github.com/metanorma/bipm-si-brochure/pull/36.

https://www.bipm.org/en/publications/rapports-bipm/ contains totally 517 rapports (searching through this link leads to https://www.bipm.org/jsp/en/SearchBIPMReport.jsp with the list of all rapports). Below is the list of the number of rapports per year, in case we need to convert documents for some specific period. Please let me know if I should proceed converting these files.

2020: 4
2019: 7
2018: 6
2016: 1
2015: 3
2013: 2
2012: 4
2011: 7
2010: 11
2009: 4
2008: 5
2007: 7
2006: 14
2005: 14
2004: 17
2003: 11
2002: 14
2001: 9
2000: 10
1999: 17
1998: 18
1997: 5
1996: 10
1995: 13
1994: 14
1993: 5
1992: 7
1991: 7
1990: 10
1989: 11
1988: 14
1987: 5
1986: 17
1985: 14
1984: 7
1983: 10
1982: 15
1981: 10
1980: 7
1979: 14
1978: 8
1977: 9
1976: 16
1975: 11
1974: 7
1973: 13
1972: 14
1971: 8
1970: 11
1969: 19
1968: 10
1967: 8
1966: 2
1964: 1

**Comment by ronaldtse** [comment]
@anermina let's convert the 2020 back to 2015 ones since they are most relevant. Let's only do the rest if we have to. Thanks!

**Comment by anermina** [comment]
Rapport 2019/05 was already converted in https://github.com/metanorma/bipm-si-brochure/blob/master/sources/mep-candela-rapport.adoc.

The rest of the rapports are added in #15 .

Closing. In case it is decided to proceed with the documents older than 2015, please reopen this issue.
