### ISSUE TITLE
Convert JCTLM samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#19]
Joint Committee for Traceability in Laboratory Medicine (JCTLM)

https://www.bipm.org/utils/en/pdf/JCTLM-EC-07_Annex_II.pdf

JCTLM Secretariat
https://www.bipm.org/utils/en/pdf/JCTLM_Sec_P-00.pdf
https://www.bipm.org/utils/en/pdf/JCTLM_Sec_P-01.pdf

JCTLM Executive Committee
https://www.bipm.org/utils/en/pdf/JCTLM_Executive_G-01.pdf
https://www.bipm.org/utils/en/pdf/JCTLM_Executive_P-00.pdf
https://www.bipm.org/utils/en/pdf/JCTLM_Executive_P-01.pdf
https://www.bipm.org/utils/en/pdf/JCTLM-EXEC-15-03.pdf

JCTLM-DBWG (Database Working Group)

https://www.bipm.org/utils/common/pdf/JCTLM/DBWG-P-00.pdf
https://www.bipm.org/utils/common/pdf/JCTLM/DBWG-P-01A.pdf
https://www.bipm.org/utils/common/pdf/JCTLM/DBWG-P-02A.pdf
https://www.bipm.org/utils/common/pdf/JCTLM/DBWG-P-02B.pdf

For metanorma/metanorma-bipm#10.

**Comment by manuel489** [comment]
[PR](https://github.com/metanorma/mn-samples-bipm/pull/21) ready for review.

**Comment by opoudjis** [comment]
@ronaldtse Are you expecting custom header for this, as they've done? A new header for each committee is quite an impost.

If there is to be custom rendering, needs new ticket.

**Comment by ronaldtse** [comment]
@opoudjis we should use the same BIPM style layout for now for BIPM committees like JCTLM.

However, the JCGM is considered a "different organization" altogether (composing of 8 separate organizations) so will use a separate style. Perhaps we can keep JCGM inside the BIPM flavor since BIPM is the secretariat.

**Comment by opoudjis** [comment]
Ugh.

I'll just shove them into default rendering for now.
