### ISSUE TITLE
Convert Guide samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#2]
https://www.bipm.org/en/committees/cc/cct/guide-its90.html

https://www.bipm.org/utils/common/pdf/ITS-90/Guide-PLTS-2000.pdf

**Comment by ronaldtse** [comment]
@manuel489 can you please help with these? Thanks!

**Comment by manuel489** [comment]
Sure, I was actually working on it already 😉

**Comment by ronaldtse** [comment]
The ITS-90 Guide contains multiple parts, metanorma-bipm needs to support parts and sub-parts, and part/sub-part titles.

**Comment by ronaldtse** [comment]
@manuel489 also these:
* https://www.bipm.org/utils/en/pdf/PLTS-2000.pdf
* https://www.bipm.org/utils/common/pdf/ITS-90/Estimates_Differences_T-T90_2010.pdf
* https://www.bipm.org/utils/en/pdf/MeP_K_Technical_Annex.pdf

This document has to be OCRed, edited, and made into a bilingual document (ping @opoudjis ):
* https://www.bipm.org/utils/common/pdf/ITS-90/ITS-90.pdf
* https://www.bipm.org/utils/common/pdf/ITS-90/EIT-90.pdf

**Comment by opoudjis** [comment]
I shall not be actioning @ronaldtse's ping. @manuel489  shall.

@manuel489 the template for bilingual documents is:

https://github.com/metanorma/bipm-si-brochure/blob/master/sources/si-brochure-bilingual.yml
https://github.com/metanorma/bipm-si-brochure/blob/master/sources/collection_cover.html

You'll need to make one of those for this bilingual document, and it will need to be compiled with:

bundle exec metanorma collection si-brochure-bilingual.yml -x xml,html,presentation,pdf -w bilingual-brochure -c collection_cover.html

Refer to https://github.com/metanorma/metanorma-cli#compile-a-document-collection-metanorma-collection, but hopefully the YML is easy to emulate.

**Comment by manuel489** [comment]
> I shall not be actioning @ronaldtse's ping. @manuel489 shall.
> 
> @manuel489 the template for bilingual documents is:
> 
> https://github.com/metanorma/bipm-si-brochure/blob/master/sources/si-brochure-bilingual.yml
> https://github.com/metanorma/bipm-si-brochure/blob/master/sources/collection_cover.html
> 
> You'll need to make one of those for this bilingual document, and it will need to be compiled with:
> 
> bundle exec metanorma collection si-brochure-bilingual.yml -x xml,html,presentation,pdf -w bilingual-brochure -c collection_cover.html
> 
> Refer to https://github.com/metanorma/metanorma-cli#compile-a-document-collection-metanorma-collection, but hopefully the YML is easy to emulate.

Ok @opoudjis 👍

**Comment by manuel489** [comment]
All samples are merged. Closing.
