### ISSUE TITLE
Convert Working Party Note samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#3]
https://www.bipm.org/utils/common/pdf/wpn/wpn-203.pdf

https://www.bipm.org/utils/common/pdf/wpn/wpn-236.pdf

https://www.bipm.org/utils/common/pdf/wpn/wpn-237.pdf

https://www.bipm.org/utils/common/pdf/wpn/wpn-238.pdf

**Comment by ronaldtse** [comment]
Let's convert these 4 documents, they are pretty short. @anermina @manuel489 can you help arrange work? Thanks.

**Comment by anermina** [comment]
I started with https://www.bipm.org/utils/common/pdf/wpn/wpn-238.pdf.

**Comment by ronaldtse** [comment]
Thanks @anermina ! Let's use `:doctype: working-party-note`.

**Comment by anermina** [comment]
Converted in #8 . Closing.
