### ISSUE TITLE
Convert Monographie sample

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#4]
https://www.bipm.org/en/publications/scientific-output/monographies-ri.html

https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-7.pdf

https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-6.pdf

https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-2.pdf

https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-1.pdf

**Comment by ronaldtse** [comment]
Let's convert 2 of these since they are really long. @anermina @manuel489 can you help arrange work? Thanks.

**Comment by anermina** [comment]
Monographie samples BIPM-1 and BIPM-6 are converted in #17 . Not closing this ticket since there are three more samples. @ronaldtse , if these two are enough, please close the ticket.

**Comment by ronaldtse** [comment]
@anermina thanks for converting Monographie 1 and 6. Having reviewed the rest, could you also help convert 2, 3, 4 and 7?

That leaves 5, which is really a database, which we won't do.

**Comment by opoudjis** [comment]
TeX, and typewriter. That's just funny.

I assume @ronaldtse there is a separate PDF (and HTML?) styling ticket?

**Comment by anermina** [comment]
Converted the rest of the samples in #25 . Closing.
