### ISSUE TITLE
Convert cipm-mra samples

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#5]
https://www.bipm.org/utils/common/documents/CIPM-MRA/CIPM-MRA-D-02.pdf

https://www.bipm.org/utils/common/documents/CIPM-MRA/CIPM-MRA-G-02.pdf

**Comment by anermina** [comment]
Converted in https://github.com/metanorma/mn-samples-bipm/pull/16. Closing.
